### ISSUE TITLE
Error for 3.6.1 sdk

### ISSUE THREAD

**Issue by umachaVail** [FreeClimbAPI/nodejs-sdk#73]
With "@freeclimb/sdk": "^3.6.0" as a dependency in this directory's package.json, I ran yarn install and this error came up. Same result on both node versions, 20.11.0 and 18.16.0. Bumping down to version 3.6.0 of the sdk works fine, so it appears changes from this [commit](https://github.com/FreeClimbAPI/nodejs-sdk/commit/8093d648bc7b15e20e1b064a80d7ac5fa17d3060) is causing an error?

 

![Screenshot 2024-08-20 at 4 38 05 PM (2)](https://github.com/user-attachments/assets/6392aad3-c034-432d-a849-d26819e85905)

**Comment by amahadaya** [comment]
Hi @umachaVail, we've released a new version for the NodeJS SDK that should resolve the issue in 3.6.1, the new version is 3.6.2, please give that version a try and let us know if we can close out the issue.

**Comment by umachaVail** [comment]
Hi @amahadaya yes the new version is working thank you
